---
apiVersion: v1
kind: Service
metadata:
  name: m-t-mysql
  labels:
    app: m-t-mysql
spec:
  type: NodePort
  ports:
  - name: m-t-mysql
    port: 3306
    protocol: TCP
    targetPort: m-t-mysql
  selector:
    app: m-t-mysql

