apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spark_master.service.name }}
  #namespace: monitoring
  labels:
    app: spark-master
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - name: master
      port: 7077
      targetPort: master
    - name: master-webui
      port: 18080
      targetPort: master-webui
    - name: block-manager
      port: 7100
      targetPort: block-manager
    - name: broadcast
      port: 7105
      targetPort: broadcast
    - name: driver
      port: 7110
      targetPort: driver
    - name: executor
      port: 7115
      targetPort: executor
    - name: fileserver
      port: 7120
      targetPort: fileserver
  selector:
    app: spark-master

