# Default values for transform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
container_name: transform
namespace: monitoring
replication_count: 1
image:
  repository: ncsmm
  name: monasca-transform
  tag: v6
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
config:
  db:
    host: m-t-mysql
    user: m-transform
    password: password
  messaging:
    metrics_topic: metrics
    metrics_pre_hourly_topic: metrics_pre_hourly
    broker: kafka:9092
  election:
    host: zookeeper
    port: 2181
  stream_interval: 600
  late_metric_slack_time: 600
spark_config:
  driver:
    extraClassPath: /opt/spark/current/lib/drizzle-jdbc-1.3.jar
    extraJavaOptions: -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/tmp/gc_driver.log -Xmx512m
    memory: 512m
  executor:
    cores: 1
    extraClassPath: /opt/spark/current/lib/drizzle-jdbc-1.3.jar
  ports:
    master: 7077
    master_web_ui: 18085
    worker: 7078
    worker_web_ui: 18086
    blockManager: 7100
    broadcast: 7105
    driver: 7110
    executor: 7115
    fileserver: 7120
    history_ui: 18082
  python:
    worker_memory: 16m
  speculation: true
  speculation_interval: 200
  sql:
    shuffle_partitions: 32
  eventLog_dir: /var/log/spark/events
  history_fs_logDirectory: file://var/log/spark/events
  log_dir: /var/log/spark
  spark_master_ip: spark-master-svc
